Type.create!([
  {TypeName: "Music"},
  {TypeName: "Podcast"},
  {TypeName: "Audiobook"},
  {TypeName: "Film Scoring"},
  {TypeName: "Movie"},
  {TypeName: "Other"}
])
Contribution.create!([
  {ContributionType: "Mastered"},
  {ContributionType: "Composed"},
  {ContributionType: "Mix Assistant"},
  {ContributionType: "Mixed"},
  {ContributionType: "Produced"},
  {ContributionType: "Co-Wrote"},
  {ContributionType: "Wrote"}
])
Award.create!([
  {AwardName: "Best Business/Finance Podcast Award", AwardLink: "https://aapodcasters.org/awards2021/", AwardYear: "2022-02-11"},
  {AwardName: "Best Business Podcast Award, IndyPopCon (2021)", AwardLink: "https://www.facebook.com/indypopcon/photos/pcb.1994308470730337/1994308167397034", AwardYear: "2021-02-11"},
  {AwardName: "Gold Award, Marcom Awards", AwardLink: "https://enter.marcomawards.com/entry/dear-workplace-podcast-by-innovatorsbox-studios-original-production-music-and-script/", AwardYear: "2021-02-11"},
  {AwardName: "Official Selection: Golden Cali Film and Art Awards", AwardLink: "", AwardYear: "2022-02-11"},
  {AwardName: "Official Selection: Chicago South Asian Film Festival", AwardLink: "", AwardYear: "2022-02-11"},
  {AwardName: "Official Selection: New Jersey Indian and International Film Festival", AwardLink: "", AwardYear: "2022-02-11"}
])
Project.create!([
  {ProjectName: "SLIPPY TOAD", ProjectLink: "https://www.youtube.com/watch?v=upKxlrGrPQI", ProjectOwner: "Bhloom", ProjectStart: "2022-01-01", ProjectEnd: "2022-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "missin you crazy (ravi's version)", ProjectLink: "https://www.youtube.com/watch?v=AmhyZDHMJKI", ProjectOwner: "ravi ray", ProjectStart: "2022-01-01", ProjectEnd: "2022-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "Redefining ABCD S3 Intro", ProjectLink: "https://www.youtube.com/watch?v=kH4YoClgFfg", ProjectOwner: "Keerthi Sekar & Sneha Ameya", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "Carol of the Bells", ProjectLink: "https://www.youtube.com/watch?v=XIqfU0NJers", ProjectOwner: "InnovatorsBox Studios", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "The Desi Condition S4 Intro", ProjectLink: "https://www.instagram.com/p/CTxIxtJLaAq/?utm_source=ig_web_copy_link", ProjectOwner: "Tanushree Sengupta", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "Here", ProjectLink: "https://www.youtube.com/watch?v=89agMs5d5do", ProjectOwner: "InnovatorsBox Studios", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "decisions", ProjectLink: "https://www.youtube.com/watch?v=XdxWJzpGpZI", ProjectOwner: "ravi ray", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "Pollen", ProjectLink: "https://www.youtube.com/watch?v=_bHLJY_Jk5M", ProjectOwner: "ravi ray", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "Salt Creek", ProjectLink: "https://www.youtube.com/watch?v=d9MRgxed06U", ProjectOwner: "Aaron Hanania & Shannon Rees", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "Intezaar", ProjectLink: "", ProjectOwner: "Kumar Roy", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "proud", ProjectLink: "https://www.youtube.com/watch?v=vmKn_C3rs10", ProjectOwner: "ravi ray", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "heartless (cover)", ProjectLink: "https://www.youtube.com/watch?v=NO33wgUx46s", ProjectOwner: "ravi ray & Ashley Bradley", ProjectStart: "2020-01-01", ProjectEnd: "2020-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "Masterpiece (cover)", ProjectLink: "https://www.youtube.com/watch?v=ADX5NKbChTM", ProjectOwner: "ravi ray", ProjectStart: "2019-01-01", ProjectEnd: "2019-01-01", ProjectDescription: "", TypeID: 1},
  {ProjectName: "South Asian Trailblazers", ProjectLink: "https://open.spotify.com/show/0iE60IOf14h5nhIABlfZQh?dl_branch=1&si=6Xf3wkw3TAqw0FF2CZ4qVQ&nd=1", ProjectOwner: "Simi Shah", ProjectStart: "2021-01-01", ProjectEnd: "2022-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "The Desi Condition", ProjectLink: "https://open.spotify.com/show/5UdzYH5e2V6b8owUtKaNnv?dl_branch=1&si=_Czm4gr7QdCefAyOv3KhuA&nd=1", ProjectOwner: "Tanushree Sengupta", ProjectStart: "2020-01-01", ProjectEnd: "2022-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "Dear Workplace", ProjectLink: "", ProjectOwner: "Monica Kang", ProjectStart: "2021-01-01", ProjectEnd: "2022-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "Curious Monica", ProjectLink: "https://open.spotify.com/show/0PJRiFhrhLRA4GxeGfkIxB?dl_branch=1&si=Qp3uTcvcSQORkRCZSpnsqQ&nd=1", ProjectOwner: "Monica Kang", ProjectStart: "2021-01-01", ProjectEnd: "2022-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "Brown People We Know", ProjectLink: "https://open.spotify.com/show/5yf5bFrkdLLax3nOv67Y0P?dl_branch=1&si=calU7ivsTw6DcoLpthdQvQ&nd=1", ProjectOwner: "Suraj Kandukuri", ProjectStart: "2021-01-01", ProjectEnd: "2022-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "South Asian Stories", ProjectLink: "https://open.spotify.com/show/0Y4Ofv9in9s83DzJCLYzer?dl_branch=1&si=cADfeS2aSsWsARXvWjU1Qg&nd=1", ProjectOwner: "Sameer Desai", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "Strong Asian Lead", ProjectLink: "https://open.spotify.com/show/5vgqPKbNlqlamSddt8vhLB?dl_branch=1&si=98M_kGVmSDSAHdRHBsKpIg&nd=1", ProjectOwner: "David Moriya", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "Neat Beans & Collard Greens", ProjectLink: "https://open.spotify.com/show/2d36BgqX1tP5ne7xaf7JIV?dl_branch=1&si=6jTBQglPRbCIoMq7mbmChw&nd=1", ProjectOwner: "David G./Bryan H.", ProjectStart: "2020-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 2},
  {ProjectName: "Rethink Creativity", ProjectLink: "Monica H. Kang", ProjectOwner: "Monica H. Kang", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 3},
  {ProjectName: "Who Will Rise Up", ProjectLink: "https://www.audible.com/pd/Who-Will-Rise-Up-Audiobook/B09FNS4Y8C", ProjectOwner: "Jed Smock", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 3},
  {ProjectName: "The Last Date", ProjectLink: "https://www.youtube.com/playlist?list=PLQTopKbVlKK4_iwLMwRomseOO18NNDHy9", ProjectOwner: "Adithya Rajan", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 4},
  {ProjectName: "Nima-Shyam Wedding", ProjectLink: "", ProjectOwner: "Sidhi Patel", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 6},
  {ProjectName: "PARTH X TEMPLE AGNI", ProjectLink: "https://www.youtube.com/watch?v=qFPKfX3wmiQ", ProjectOwner: "Parth Patel", ProjectStart: "2021-01-01", ProjectEnd: "2021-01-01", ProjectDescription: "", TypeID: 6},
  {ProjectName: "The Desi Condition S3 Intro", ProjectLink: "https://www.instagram.com/p/CBWF1T7lMft/?utm_source=ig_web_copy_link", ProjectOwner: "Tanushree Sengupta", ProjectStart: "2020-01-01", ProjectEnd: "2020-01-01", ProjectDescription: "", TypeID: 6}
])
Awarded.create!([
  {AwardedDate: "2022-02-11", AwardID: 1, ProjectID: 16, awards_id: 1, projects_id: 1},
  {AwardedDate: "2022-02-11", AwardID: 2, ProjectID: 16, awards_id: 1, projects_id: 1},
  {AwardedDate: "2022-02-11", AwardID: 3, ProjectID: 16, awards_id: 1, projects_id: 1},
  {AwardedDate: "2022-02-11", AwardID: 4, ProjectID: 24, awards_id: 1, projects_id: 1},
  {AwardedDate: "2022-02-11", AwardID: 5, ProjectID: 24, awards_id: 1, projects_id: 1},
  {AwardedDate: "2022-02-11", AwardID: 6, ProjectID: 24, awards_id: 1, projects_id: 1}
])
DisplayLine.create!([
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 1), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 2), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 2), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 3), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 3), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 3), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 4), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 4), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 5), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 5), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 5), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 6), Contribution: Contribution.find_by(id: 6)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 7), Contribution: Contribution.find_by(id: 7)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 7), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 8), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 8), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 9), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 9), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 10), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 10), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 11), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 11), Contribution: Contribution.find_by(id: 7)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 12), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 12), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 13), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 13), Contribution: Contribution.find_by(id: 5)},
  {ComponentContributed: "S3 all episodes, S4 all episodes", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 14), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "S3 all episodes, S4 all episodes", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 14), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "S2 ep. 12/15, S3 all episodes, S4 all episodes", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 15), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "S2 ep. 12/15, S3 all episodes, S4 all episodes", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 15), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "S1 all episodes, S2 ep. 2-10", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 16), Contribution: Contribution.find_by(id: 3)},
  {ComponentContributed: "S1 all episodes, S2 all episodes", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 17), Contribution: Contribution.find_by(id: 3)},
  {ComponentContributed: "S1 ep. 24-34", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 18), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "S1 ep. 24-34", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 18), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "S1 ep. 30-32", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 19), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "S1 ep. 30-32", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 19), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "S1 ep. 5-12", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 20), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "S1 ep. 5-12", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 20), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "S1 all episodes", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 21), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "S1 all episodes", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 21), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 22), Contribution: Contribution.find_by(id: 3)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 23), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 23), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "Short Film", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 24), Contribution: Contribution.find_by(id: 2)},
  {ComponentContributed: "Short Film", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 24), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "Short Film", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 24), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "Bollywood Mashup", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 25), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "Bollywood Mashup", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 25), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "Bollywood Mashup", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 26), Contribution: Contribution.find_by(id: 4)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 27), Contribution: Contribution.find_by(id: 1)},
  {ComponentContributed: "", ComponentStartDate: "2022-02-11", ComponentEndDate: "2022-02-11", Project: Project.find_by(id: 27), Contribution: Contribution.find_by(id: 4)}
])
